# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'JWPlayerDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JWPlayerDemo
  pod 'JWPlayer-SDK', '2.2.1'

  target 'JWPlayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'JWPlayer-SDK', '2.2.1'
  end

end
